### ISSUE TITLE
Reset Demo - reset the workflow state only when running "Run All"

### ISSUE THREAD

**Issue by adt-apjc** [adt-apjc/YAP#100]
I think the project action should be to reset the demo when all pre-check/actions/post-checks are execute successfully

**Comment by adt-apjc** [comment]
Agreed to add a "Wipe Variable" checkbox default to check that if unchecked runs the actions without cleaning the environment.

**Comment by davyvine** [comment]
- removed the "outcome" section for "stage, cleanup and unstage"
- removed the "burger" icon or the show preface option for "stage, cleanup and unstage"
- clear var checkbox is only available on "cleanup"

**Comment by adt-apjc** [comment]
We shall remove Preface Reference from "stage, cleanup and unstage" edit mode, now that they don't support anymore this feature.

![Image](https://github.com/adt-apjc/YAP/assets/99869031/ff7b5e1e-10ae-4390-8188-0336c9c13755)
