### ISSUE TITLE
Enhance actions with javascript processing instead of regexp

### ISSUE THREAD

**Issue by adt-apjc** [adt-apjc/YAP#106]
Current YAP is supporting regexp for selecting sub-string from API body response. YAP is not supporting running logic because it focuses on clean static presentations but from initial discussion with stakeholder, we see the need to start supporting some text manipulation and we should assess an option to execute javascript code in the application.

This add some security concerns, considering that we run YAP in docker and we must remember that this enhancement open the door to abuse.

**Comment by marumer** [comment]
To be tracked in ideas
