### ISSUE TITLE
UI gap - expose support for hierarchical objects

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#109]
YAP support the concept of hierarchy in the outcome objects, using the parent field to refer to the higher hierarchy object.

This can be handy to target command to different objects like in the APIC demo.
![image](https://github.com/adt-apjc/YAP/assets/12079368/47862f83-e2d4-4daf-a359-f7c82c0a8e56)

![image](https://github.com/adt-apjc/YAP/assets/12079368/ffb05aa9-8de1-41da-a44e-82fbb1061a55)

**Comment by ueasaksupa** [comment]
![image](https://github.com/adt-apjc/YAP/assets/4270762/8d261cd1-55e3-41cf-8793-8619c300e403)

v 1.1.1 compound node form

**Comment by marumer** [comment]
I like what you proposed and it works well. As we suggest the Default icon, which make perfect sense for a container, how can we replicate the same experience from the UI and create a square instead of the proposed circle when adding a new object that we can not modify the dimentions.

![image](https://github.com/adt-apjc/YAP/assets/12079368/0ffdda0c-523d-415c-a9c7-1b9f5b539fa4)

**Comment by marumer** [comment]
Discussed that the rectangular object is rendered when it becomes a parent of another object
