### ISSUE TITLE
UI support to reorganise preface order (#111 dependency)

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#112]
As for steps, YAP UI does't support the reorganisation of the preface with new steps, forcing manual modification of the JSON.
The prefaceRef on the project's steps, make very flexible point to different places of the preface but complicate this issue because changes in the preface order, would mess up configured prefaceRef if not updated accordingly.

Lower priority issue because we can overcome preface order with some UI copy and paste.

**Comment by davyvine** [comment]
prefaceRef will update accordingly when the preface tabs are re-arranged

example:
1. "Device Onboarding" is moved to the very end
<img width="1699" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/9cd9b384-47c8-4645-9e54-cae2fa0673f7">
<img width="1705" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/a9d011a5-feac-4baa-b489-0c3cf8d40b94">

2. checking the prefaceRef, you can see it's updated accordingly
<img width="1517" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/845953e9-7acb-4e4e-ac06-f0153f0297ac">
<img width="1690" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/cc424524-468a-4158-84a9-de3c76d4345a">

You can check for other steps that prefaceRef has been updated correctly
