### ISSUE TITLE
Control Clean Up "Clear Variables" from the demo JSON

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#115]
I agree that using "Clear Variables" checked as default is the right option but I would suggest to expose it in the JSON (to be moved to 1.0.1 version) for the cleanup special step. I am suggesting this because of the use case to use this step to process authentication and it would be confusing for user missing Notes to uncheck this field.

**Comment by davyvine** [comment]
Updated CNC demo config with "clearVariables": false and updated the json version to 1.0.2. Kindly pull latest config from YAP ZOO when testing.
