### ISSUE TITLE
Add an optional TCP port fort the ssh session

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#121]
![image](https://github.com/adt-apjc/YAP/assets/12079368/e7a6f6d8-93ef-4022-92e0-ae56874b17a2)

YAP shall be able able to open an SSH session toward a non standard port. The first use case is to access NSO cli portal

**Comment by marumer** [comment]
To discuss a workaround for NSO (current main use case for this feature) and if we need to add more option for the  algorithm

testing toward dCloud demo 198.18.134.28 -p 2024, getting

*** SSH CONNECTION ERROR: Handshake failed: no matching key exchange algorithm ***
*** SSH CONNECTION CLOSED ***

Can be replicated from personal ssh and works with:
ssh -o KexAlgorithms=diffie-hellman-group14-sha1 admin@198.18.134.28 -p 2024

**Comment by ueasaksupa** [comment]
On this issue, I decided not to add more options about SSH config, but I appended the KEX algorithm to the support list
this is what we currently support about SSH config.
> **cipher** 
- aes128-gcm
- aes128-gcm@openssh.com
- aes256-gcm
- aes256-gcm@openssh.com
- aes128-ctr
- aes192-ctr
- aes256-ctr
> **kex**
- curve25519-sha256 (node v14.0.0+)
- curve25519-sha256@libssh.org (node v14.0.0+)
- ecdh-sha2-nistp256
- ecdh-sha2-nistp384
- ecdh-sha2-nistp521
- diffie-hellman-group-exchange-sha256
- diffie-hellman-group14-sha256
- diffie-hellman-group15-sha512
- diffie-hellman-group16-sha512
- diffie-hellman-group17-sha512
- diffie-hellman-group18-sha512
- diffie-hellman-group14-sha1
>**serverHostKey**
- ssh-ed25519
- ecdsa-sha2-nistp256
- ecdsa-sha2-nistp384
- ecdsa-sha2-nistp521
- rsa-sha2-512
- rsa-sha2-256
- ssh-rsa

**Comment by marumer** [comment]
Tested on NSO embedded in the CNC demo and it works like a charm !!!
