### ISSUE TITLE
Executing a second command re-render the request payload still showing the previous outcome

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#132]
After executing "show segment-routing traffic-eng policy"
![image](https://github.com/adt-apjc/YAP/assets/12079368/76f7c912-f15b-4203-8def-f4fc15ae4f4e)

I am selecting the next command "show segment-routing traffic-eng on-demand color" and YAP rerender the request payload
![image](https://github.com/adt-apjc/YAP/assets/12079368/8d8c15e0-9656-4cd6-8514-f6444a57daef)

before issuing the command, that when run would return
![image](https://github.com/adt-apjc/YAP/assets/12079368/bd7a04e7-e354-473f-b24b-72c27f94d1d8)

**Comment by ueasaksupa** [comment]
I dont understand this i think the payload of the request is correct change, but we should clear the response when user change the command
