### ISSUE TITLE
Extend Endpoint with Command endpoint

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#171]
Currently YAP support only API endpoint and we need a new group to support SSH command

- Extend the data structure to support a new commandEndpoints section (we may keep the current endpoints list for API endpoint to be backward compatible)
- Rename the current UI Setting/Endpoint section to API Endpoint (or similar)
- Rename any reference to Endpoint through the application to API Endpoint
- Create a new group "Command Endpoint" in Settings using the same CRUD UI experience used for API endpoint 
- We may support username/password initially and planning as InFusion for certificates in a separate task
- We should support the same SSH options as implemented for topology commands

<img width="994" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/50fd4d9a-dd07-49f6-83aa-a8943dfbe8ee">

**Comment by ueasaksupa** [comment]
I think we better call it "CLI Endpoint" because the term "Command" is already used in Outcome command.
and change from commandEndpoints to cliEndpoints or sshCliEndpoints
