### ISSUE TITLE
UI action presentation

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#176]
When presenting a command action:
- we can leave the Endpoint, Variable and Expect objects
- we should remove the API URI string
- the command payload and response should be multiline text sections
- the response will consolidate STD out and error
- we should still render the response code returned from by the backend
- the action should be validated follow the expect condition (supporting multiple body contain/not contain statements in AND)

<img width="729" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/a1029928-c3fb-47ac-b3c6-09b702608760">

**Comment by ueasaksupa** [comment]
need to improve color scheme text from linux terminal



![Image](https://github.com/adt-apjc/YAP/assets/4270762/7c54378a-215b-4f51-89e6-1a1f69a541f4)
