### ISSUE TITLE
Validate backendRequest

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#200]
Did we remove support API without backendRequest? 
I am asking because we append "/proxy/request`" when backendRequest or backendRequest === undefined
 

![Image](https://github.com/adt-apjc/YAP/assets/12079368/d5246d3b-11c2-449c-a464-80269b05d978)

**Comment by ueasaksupa** [comment]
Currently, the UI doesn't support changing the backendRequest (and we don't have the use case for that)
so we are agreed to just leave a note comment in the code.
