### ISSUE TITLE
Improve UX for left menu to provide clue that this is a sequential workflow

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#40]
Considerations to elevate the tool for a higher level presentation, current UX already good for engineering presentation

YAP support skipping steps and this is useful when preparing or testing a demo, still the natural demo flow will be a sequential flow from the first step to the last.

The current UX may be improved to drive the user in the experience.
![image](https://github.com/adt-apjc/YAP/assets/12079368/607bb476-7804-4108-bf19-d6147ca40f51)

Using the vertical space has the advantage to support several steps for longer demos and fits well with this application realestate.

Something like this is close to the current look
![image](https://github.com/adt-apjc/YAP/assets/12079368/b090fc5f-a1ec-4e9f-a945-03da1942c2e5)
![image](https://github.com/adt-apjc/YAP/assets/12079368/c71beec5-2495-4c21-be4e-a2c6db025320)

For the demo introduction an horizontal, aligned to the left may help to provide clues about the demos and link the step number with the number on the left menu.
- (separate note) for the text description, we should add a bit of extra vertical padding because the text is a bit squeezed.

![image](https://github.com/adt-apjc/YAP/assets/12079368/13ca98ef-4531-451d-8802-1515b1992898)

![image](https://github.com/adt-apjc/YAP/assets/12079368/8a1f17ce-52a7-46f3-9261-67bf145c749c)

**Comment by adt-apjc** [comment]
should we make the circle around the number green as the check when checked?
![image](https://github.com/adt-apjc/YAP/assets/99869031/48df1083-a589-496e-8907-b2e8f5c7034e)
