### ISSUE TITLE
Provide access to the Step summary slides in the Step

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#47]
YAP currently support the introduction to explain the flow before starting but force the presenter to switch between the step and the introduction, if receive questions or he want to presented each context sequentialy.

<img width="1706" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/b09fd42e-40fa-496c-a4d6-f6c141b2b860">

We should add to each step the same information, accessible from a curtain by clicking on a help button, maybe close to the "Run All"
<img width="1706" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/3c53ff69-fbaf-4753-8e7f-c7a6c7549aa9">

**Comment by marumer** [comment]
![Image](https://github.com/adt-apjc/YAP/assets/12079368/76a0ba9a-c82d-4467-a75e-4292f295cfaa)


move arrow icon from the top to the middle of the area to avoid interference with the title. 
Proposed icon may be a bit higher but thinner horizontally.

**Comment by ueasaksupa** [comment]
![Image](https://github.com/adt-apjc/YAP/assets/4270762/32e357b2-5269-47ff-9796-0aa77eb8300c)

color of the content body and tab header should be the same

**Comment by davyvine** [comment]
I decided to put the "show step summary button" next to the "run all" icon for a cleaner look. We can also add more actions in the same row in the future..

<img width="1706" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/f0624f74-e62d-4180-b666-affec8c5d1b3">

<img width="1706" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/86a9c708-e6da-4ac7-8782-855c6af1e22b">

**Comment by marumer** [comment]
I like the new proposal :-)
