### ISSUE TITLE
Add option to inject global variable 

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#50]
Add to the a new Variable form accessible from the new burger menu to inject env variables.
We already support extraction of text to create variable and visualisation that should not be impacted but may use an show these variables.

We are hardcoding the name services and options in the API but sometime you want to show that they are not hardcoded and how easy is to customise a different experience by changes these variables.

**Comment by marumer** [comment]
Extend setting with Global Variable section to visualize/add/change manually configured variables
![Image](https://github.com/adt-apjc/YAP/assets/12079368/9ebd904c-9b97-4ffe-8a68-33f6374d9857)

Extend configuration and context with globalVariables array with key/value objects 
![Image](https://github.com/adt-apjc/YAP/assets/12079368/64226641-a5a1-4bee-a9af-8734a9757e07)

**Comment by davyvine** [comment]
Added new object "globalVariables" in config.json with sample key value pair for testing..
![image](https://github.com/adt-apjc/YAP/assets/53292972/a785fba4-91fe-4da6-828c-314286fa1cf4)

Visualize the global vars  in "variables"  badge under each API when available
<img width="1695" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/7457d2a1-feb7-4653-9664-ce81ea6f1f27">

**Comment by marumer** [comment]
It looks nice but we need to adjust few minor things:

1 ) We should not render a global variable if it is not part of the URL or payloads because some workflows may have a long list of variables and this would pollute the visualization object. 
![Image](https://github.com/adt-apjc/YAP/assets/12079368/192209ed-20cf-40e7-a03d-b2da727472f1)

2) I like the separation between variables but both are considering that both are global variables, maybe it is better to call the top list as Static Variables.

3) As for the end point, I should be able to click in setting on the variable and update its value.
![Image](https://github.com/adt-apjc/YAP/assets/12079368/f3207562-bb82-46c3-9847-16f4c3e181c1)

4) We need to validate that static variable are applied to url and payload 
![Image](https://github.com/adt-apjc/YAP/assets/12079368/4ef77057-c258-4a18-ba64-d3ecd709dea3)
