### ISSUE TITLE
Loading of customer icons (complement  #22)

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#51]
We may load from a remote bucket but we may explore loading from a directory shared in docker-compose or from a local directory in the user machine for simple or last minute personal customisation.

- consider option to select a local directory to load from.

**Comment by marumer** [comment]
For this sprint we are just going to document how to use local asset in a personal build or embed remote images in JSON file

**Comment by marumer** [comment]
We have still to expose this in the UI and support examples like (from the multi domains slicing demo):

![image](https://github.com/adt-apjc/YAP/assets/12079368/4f961e25-e771-4e51-b69a-048c06d35ae8)

**Comment by davyvine** [comment]
#51 modify editOutcome modal to support labelClass and icon link
 Commit ID: 4491aca3d1e881e3599af317e91c4b27b17089ea

**Comment by davyvine** [comment]
I realized that the "preview" of icon that macro suggested is already supported.

1. Edit outcome modal > create a new icon by filling out the details > CLICK "ADD" and the icon is shown under "PREVIEW" section below

<img width="1201" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/e9f79ff9-86fd-46ca-a415-eb58108727ee">

<img width="1198" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/9caa9b75-3de2-4701-a582-c09b6d95cadb">

**Comment by marumer** [comment]
Vine commented: I realized that the "preview" of the icon that Marco suggested is already supported. I didn't implement it because it would be redundant.
I agree that the tool is supporting a good preview of the outcome, but my comment was about the Appearance drop box and the fact that we need to click on Add and generate an actual object in the canvas to see how the default icon looks like.

We should also consider that maybe the term Default Icon vs Icon Link, could be more appropriate that Appearance.

**Comment by davyvine** [comment]
#51 outcome editor enhancements CommitID: 54ee1c773faf06f9b79903caac567777fab145e2

**Comment by davyvine** [comment]
Marco's comment above and Additional Feedback below are implemented.
- Rename "Label Class" to "Label Position"
- Rename all options of "Label Position" ie. "labelBottom" change to "Bottom" 
- Add another "Label Position" option  'Center'.
- Generalize the "cloud" icon label position to "Top". Previously the default was "center".
- Add "Text" option for "Built-In Icons"
- Fix "Built-In Icons" "Default" shape to ellipse
- Add Validation for  Icon Link input
