### ISSUE TITLE
can not load images from public assets 

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#71]
Commit d3bb8339fb2fcbb2e3592eb0bbe22bc8ad06b893 [d3bb833] broke SR/ACI demo flow be removing asset and making available unusable in preface. 

<img width="1168" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/64fe115e-5114-45d7-8b49-828389a191ed">
<img width="1529" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/c055f5b3-249f-490b-b98f-fef25b5b6076">

to text we can use https://wwwin-github.cisco.com/APJ-GSP-ADT/YAP-Zoo/blob/master/YAP_New_Format/multi_domain_sr_aci.json

**Comment by marumer** [comment]
agreed to rollback changes on assets and remove app from cluster

**Comment by ueasaksupa** [comment]
fix 4e0ca840faadf2036b6b9159c518c644f95cdb0e
