### ISSUE TITLE
Enhance outcome with option to initiate a ssh session to a remote device in the canvas (#76)

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#77]
Today we execute only command on a object in the canvas but it will be important to engineers being able to open one or more floating terminal toward a remote node or edge in the canvas.\

Following on the conversation with the demo stakeholder, this feature shall be prioritised because it differentiate YAP and it is suitable to some of the RON demo.

**Comment by ueasaksupa** [comment]
@marumer SSH is now usable you can verify by adding SSH info in the outcome editor
![image](https://github.com/adt-apjc/YAP/assets/4270762/373a5561-e043-47de-9227-605967a0deed)

after you added it, it will show here
![image](https://github.com/adt-apjc/YAP/assets/4270762/304e3427-f2a0-4231-9d5c-8a25f748e41a)
