### ISSUE TITLE
Generalise processing of username and password variables

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#93]
Currently YAP process the username and password variables to generate the basic auth but this may confuse a users and we should extend the endpoint with options to specify the variable name to use for this processing

<img width="828" alt="image" src="https://github.com/adt-apjc/YAP/assets/12079368/4c20eed4-fc80-484c-abf8-fd7ad57c0d9a">

![image](https://github.com/adt-apjc/YAP/assets/12079368/6c301d90-dc5a-41b3-b527-f65b966d2c8f)

**Comment by adt-apjc** [comment]
Can you please update this case with few lines describing how this task has been achieved and how the user shall configure the basic auth.
