### ISSUE TITLE
Expose prefaceRef in the UI

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#96]
YAP supports prefaceRef to synchronise the step help with the preface index but it doesn't expose the field in the UI. 

```
      "step_2": {
         "description": "Device Onboarding (optional)",
         "continueOnFail": false,
         "prefaceRef": 3,
```

We may consider to expose this field as text or drop box to choose from the preface array configured options when in Edit mode in a Step window. For example below the title and before the multiline text.

![image](https://github.com/adt-apjc/YAP/assets/12079368/7527dc1a-a8ce-455c-a106-61f50ac705e6)

**Comment by adt-apjc** [comment]
This works nice and it is now easy to update and find errors
